KEY_PREFIX = "com.github.developerutils.docker-gen"
KEY_ENABLED = KEY_PREFIX + ".enabled"
KEY_OUTBOUND = KEY_PREFIX + ".outbound"
KEY_URL = KEY_PREFIX + ".url"
KEY_FORWARD_PORT = KEY_PREFIX + ".exposed-port"
KEY_SSL_ENABLED = KEY_PREFIX + ".ssl.enabled"
KEY_SSL_CERT_KEY = KEY_PREFIX + ".ssl.cert_path.key"
KEY_SSL_CERT_CRT = KEY_PREFIX + ".ssl.cert_path.crt"
