KEY_PREFIX = "com.github.developerutils.docker-gen"
KEY_ENABLED = KEY_PREFIX + ".enabled"
KEY_OUTBOUND = KEY_PREFIX + ".outbound"
KEY_URL = KEY_PREFIX + ".url"
KEY_FORWARD_PORT = KEY_PREFIX + ".exposed-port"
